import markdown2
from weasyprint import HTML, CSS
from fastapi.responses import StreamingResponse
from io import BytesIO
from datetime import datetime
from fastapi import HTTPException
import logging
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
static_dir = os.path.join(current_dir, "static")
logo_path = os.path.join(static_dir, "logo.png")

# Configure logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)  # Ensure logger is configured

def markdown_to_pdf(md_content: str, domain: str, report_type: str):
    """Convert markdown content to a styled PDF with security headers."""
    try:
        if not md_content or not isinstance(md_content, str):
            raise ValueError("Invalid Markdown content provided")

        # Convert Markdown to HTML with extended features
        html_content = markdown2.markdown(
            md_content,
            extras=["tables", "fenced-code-blocks", "header-ids", "footnotes"]
        )

        # Calculate the path to the static directory containing the logo
        current_dir = os.path.dirname(os.path.abspath(__file__))
        static_dir = os.path.join(current_dir, "static")

        # Enhanced HTML template with logo and "Generated by RECONNAITY" adjusted
        styled_html = f"""
        <style>
            @page {{
                size: A4;
                margin: 2cm;
                @bottom-right {{
                    content: "Page " counter(page) " of " counter(pages);
                    font-size: 10pt;
                    color: #666;
                }}
            }}
            body {{
                font-family: 'Arial', 'Helvetica', sans-serif;
                line-height: 1.6;
                color: #333;
                margin: 20px;
            }}
            /* Report Header */
            .report-header {{
                background: linear-gradient(90deg, #2E4053, #3498DB);
                color: white;
                padding: 15px;
                border-radius: 8px;
                margin-bottom: 30px;
                position: relative;
            }}
            .report-header .logo {{
                position: absolute;
                top: 15px;
                left: 15px;
                width: 47px;
                height: auto;
            }}
            .report-header .slogan {{
                text-align: center;
                font-size: 12pt;
                font-weight: bold;
                color: #FFF;
                margin: 0 0 15px 0;  /* Bottom margin controls space to title */
            }}
            .report-header h1 {{
                color: #FFF;
                border-bottom: 3px solid #2E86C1;
                padding-bottom: 8px;
                margin-top: 0;  /* Reduced from 2rem to bring title closer */
                text-align: center;
            }}
            .report-header p {{
                margin: 5px 0;
                font-size: 12pt;
                text-align: center;
            }}
            /* Section Headers */
            h2 {{
                color: #3498DB;
                border-left: 5px solid #2E86C1;
                padding-left: 10px;
                margin: 25px 0 15px;
            }}
            h3 {{
                color: #884EA0;
                margin: 20px 0 10px;
                border-bottom: 1px dotted #884EA0;
            }}
            /* Lists */
            ul, ol {{
                list-style-position: outside;
                margin: 15px 0;
                padding-left: 30px;
            }}
            ul li {{
                list-style-type: disc;
                margin-bottom: 8px;
                display: list-item;
                visibility: visible;
                overflow: visible;
            }}
            ol li {{
                list-style-type: decimal;
                margin-bottom: 8px;
                display: list-item;
                visibility: visible;
                overflow: visible;
            }}
            /* Severity Colors */
            .critical {{ 
                color: #C0392B; 
                font-weight: bold; 
                background: #FFEBEE; 
                padding: 2px 5px; 
                border-radius: 3px; 
            }}
            .high {{ 
                color: #E67E22; 
                font-weight: bold; 
                background: #FFF3E0; 
                padding: 2px 5px; 
                border-radius: 3px; 
            }}
            .medium {{ 
                color: #F1C40F; 
                font-weight: bold; 
                background: #FFFDE7; 
                padding: 2px 5px; 
                border-radius: 3px; 
            }}
            /* Tables */
            table {{
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
                font-size: 10pt;
                page-break-inside: auto;
            }}
            th {{
                background: #2E4053;
                color: white;
                padding: 12px;
                text-align: left;
            }}
            td {{
                border: 1px solid #DDD;
                padding: 8px;
                vertical-align: top;
            }}
            tr {{
                page-break-inside: avoid;
                page-break-after: auto;
            }}
            tr:nth-child(even) {{
                background: #F9F9F9;
            }}
            /* Code Snippets */
            pre {{
                background: #2D2D2D;
                color: #FFF;
                padding: 12px;
                border-radius: 6px;
                margin: 15px 0;
                font-family: 'Courier New', 'Courier', monospace;
                white-space: pre-wrap;
                overflow: visible;
                visibility: visible;
                font-size: 10pt;
                line-height: 1.4;
            }}
            code {{
                font-family: 'Courier New', 'Courier', monospace;
                background: #F8F9FA;
                padding: 3px 6px;
                border-radius: 4px;
                color: #333;
                display: inline;
                white-space: pre-wrap;
                overflow: visible;
                visibility: visible;
                font-size: 10pt;
                line-height: 1.4;
            }}
            /* Warnings */
            .warning {{
                background: #FFD7D7;
                border-left: 6px solid #C0392B;
                padding: 15px;
                margin: 20px 0;
                border-radius: 4px;
            }}
            /* Executive Callouts */
            .callout-red {{
                color: #C0392B;
                font-weight: bold;
                padding: 8px 12px;
                border-radius: 4px;
                background: #FFEBEE;
                margin: 10px 0;
            }}
            .callout-orange {{
                color: #E67E22;
                padding: 8px 12px;
                border-radius: 4px;
                background: #FFF3E0;
                margin: 10px 0;
            }}
            .callout-green {{
                color: #229954;
                padding: 8px 12px;
                border-radius: 4px;
                background: #E8F8EC;
                margin: 10px 0;
            }}
            /* Mermaid Diagrams */
            .mermaid {{
                background: #F8F9FA;
                padding: 15px;
                border: 1px solid #DDD;
                border-radius: 6px;
                margin: 20px 0;
                font-family: 'Courier New', 'Courier', monospace;
            }}
            /* Links */
            a {{
                color: #3498DB;
                text-decoration: none;
                border-bottom: 1px dashed #3498DB;
            }}
            a:hover {{
                border-bottom: 1px solid #2980B9;
            }}
            /* Special Symbols */
            .arrow-symbol {{
                color: #3498DB;
                font-weight: bold;
                margin: 0 5px;
            }}
            /* Footer */
            footer.compliance {{
                margin-top: 30px;
                text-align: center;
                font-size: 9pt;
                color: #666;
                border-top: 1px solid #DDD;
                padding-top: 10px;
            }}
        </style>
        <div class='report-header'>
            <img src="logo.png" alt="RECONNAITY Logo" class="logo">
            <p class="slogan">Generated by RECONNAITY</p>
            <h1>{report_type}</h1>
            <p style="font-size: 10pt;">{domain} | Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
        </div>
        <div class='warning'>
            ⚠️ This report is intended solely for educational purposes and authorized activities. It must not be used for any unauthorized, illegal, or unethical actions. By proceeding, you confirm your adherence to all applicable laws, ethical guidelines, and organizational policies.
        </div>
        {html_content}
        <footer class='compliance'>
            <div>Note: With Great Power, Comes Great Responsibility :3</div>
        </footer>
        """

        # Generate PDF bytes using WeasyPrint with base_url set to the static directory
        pdf_bytes = HTML(string=styled_html, base_url=static_dir).write_pdf()

        filename = (
            f"{domain.replace(' ', '_')}_{report_type.lower()}_"
            f"{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
        )

        return StreamingResponse(
            BytesIO(pdf_bytes),
            media_type="application/pdf",
            headers={
                "Content-Disposition": f"attachment; filename={filename}",
                "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'",
                "X-Content-Type-Options": "nosniff",
                "X-Frame-Options": "DENY"
            }
        )

    except Exception as e:
        logger.error(f"PDF generation failed: {str(e)}")
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {str(e)}")